name: Android CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          git clone https://github.com/icarohs7/unox-buildsrc buildSrc
          ./gradlew -p core -Pcoverage clean build jacocoTestReport -x lint --stacktrace
          ./gradlew -p scheduling -Pcoverage clean build jacocoTestReport -x lint --stacktrace
          ./gradlew -p benchmark -Pcoverage clean build jacocoTestReport -x lint --stacktrace
          ./gradlew -p spinner -Pcoverage clean build jacocoTestReport -x lint --stacktrace
          ./gradlew -p notification -Pcoverage clean build jacocoTestReport -x lint --stacktrace
          ./gradlew -p rx -Pcoverage clean build jacocoTestReport -x lint --stacktrace
      - name: Send coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)